# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tCrunch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tCrunch

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'IQKeyboardManagerSwift'

  target 'tCrunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tCrunchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
